package com.pluralsight.streams;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
/**
 * Program to drive streams workbook exercises
 * (belonging to package: com.pluralsight.streams).
 *
 * @author Ravi Spigner
 */
public class Program {
    public static void main(String[] args) {
        List<Person> people = new ArrayList<>();
        //names below generated by ChatGPT
        people.add(new Person("Aiden","Walker", 28));
        people.add(new Person("Lila","Morgan", 24));
        people.add(new Person("Caleb","Brooks", 31));
        people.add(new Person("Sofia","Reed", 26));
        people.add(new Person("Caleb","Hunt", 29));
        people.add(new Person("Maya","Foster", 22));
        people.add(new Person("Caleb","Perry", 27));
        people.add(new Person("Nora","Hayes", 25));
        people.add(new Person("Owen","Walker", 30));
        people.add(new Person("Zoe","Walker", 23));

        Scanner scanner = new Scanner(System.in);
        System.out.print("Please enter a name to search: ");
        String searchName = scanner.nextLine();
        System.out.println();
        System.out.println("----Name Matches Found----");
        people.stream().filter(person -> person.getFirstName().equalsIgnoreCase(searchName)
                || person.getLastName().equalsIgnoreCase(searchName)).forEach(System.out::println);
        System.out.println("----Average Age----");
        double totalAllAges = people.stream().map(Person::getAge).reduce(0, Integer::sum);
        System.out.println(totalAllAges / people.size()); //print average age
        System.out.println("----Youngest Age----");
        //Person defaultPerson = people.get(0);
        //Person youngest = people.stream().min(Comparator.comparingInt(Person::getAge)).orElse(defaultPerson);
        //System.out.println(youngest);
        int defaultAge = people.get(0).getAge();
        //print youngest age
        int youngestAge = people.stream().map(Person::getAge).min(Integer::compare).orElse(defaultAge);
        System.out.println(youngestAge);
        System.out.println("----Oldest Age----");
        //Person oldest = people.stream().max(Comparator.comparingInt(Person::getAge)).orElse(defaultPerson);
        //System.out.println(oldest);
        //print oldest age
        int oldestAge = people.stream().map(Person::getAge).max(Integer::compare).orElse(defaultAge);
        System.out.println(oldestAge);
    }
}
